### ISSUE TITLE
AttributeError: module `pyccolo` has no attribute `argument`

### ISSUE THREAD

**Issue by shreyashankar** [ipyflow/ipyflow#105]
![image](https://user-images.githubusercontent.com/6224969/176323332-89779664-41b0-499f-8247-19cdfc0080a6.png)

This comes up when installing via `pip install nbsafety` in a conda environment with python 3.9, and then starting jupyterlab

**Comment by smacke** [comment]
Hey @shreyashankar, thanks for surfacing this. I think this should be fixed in the latest release of `ipyflow`, as I'm now pinning the pyccolo dependency to avoid these sorts of compat issues. I'll go ahead and close this out, but please do let me know if you experience other installation issues.
