### ISSUE TITLE
Overlaping names collide

### ISSUE THREAD

**Issue by twolodzko** [ipyflow/ipyflow#128]
It is shown in the example below where the first `x` is changed.

![Screenshot from 2023-05-10 14-17-02](https://github.com/ipyflow/ipyflow/assets/3750140/d498a3cf-8441-49ce-ae21-6fbf776fc4b0)
![Screenshot from 2023-05-10 14-17-10](https://github.com/ipyflow/ipyflow/assets/3750140/1702f794-7619-4354-aaea-d0e0738025a9)

I'd expect that everything after the second `x` would not change.

**Comment by smacke** [comment]
Thanks for reporting; I will get this fixed later today :)

**Comment by smacke** [comment]
I just pushed a fixed and cut a release; you can pick it up with
```
pip install --upgrade ipyflow
```
