### ISSUE TITLE
Attribute access can break dependency analysis

### ISSUE THREAD

**Issue by ForceBru** [ipyflow/ipyflow#157]
Attribute access like `(complicated + expression).attribute` removes the cell's dependence on cells defining `complicated` and `expression`.

![bug](https://github.com/ipyflow/ipyflow/assets/8695383/e63f77c2-3409-4a11-85e8-39bff2e6ed72)

- __Expected behavior__: with cell 9 highlighted, cells 1 and 2 (that define `a` and `b`) should have purple dots. If cells 1 or 2 are updated, cell 9 should be updated too due to reactivity.
- __Observed behavior__: cells 1 and 2 don't have purple dots, cell 9 is treated as independent, but it isn't. When cells 1 or 2 change, cell 9 is _not_ re-executed.

Simpler expressions like `a.attribute` work fine.

Full notebook: [Untitled.ipynb.gz](https://github.com/ipyflow/ipyflow/files/14638887/Untitled.ipynb.gz)

-------

Installed packages related to Jupyter:

```
> pip list | grep "ipy\|jupyter"
ipyflow                   0.0.198
ipyflow-core              0.0.198
ipykernel                 6.29.3
ipython                   8.22.2
ipython-genutils          0.2.0
ipywidgets                8.1.2
jupyter                   1.0.0
jupyter_client            8.6.1
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.9.1
jupyter-lsp               2.2.4
jupyter_server            2.13.0
jupyter_server_terminals  0.5.3
jupyterlab                4.1.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.4
jupyterlab_widgets        3.0.10
```

**Comment by smacke** [comment]
Thanks for reporting the issue! I just pushed a fix + new release (0.0.199), you should be able to grab it with `pip install --upgrade ipyflow`
