### ISSUE TITLE
"file changed on disk" popup Regression

### ISSUE THREAD

**Issue by quantum-byte** [ipyflow/ipyflow#158]
Hi,

i just tried your library. Pretty cool stuff! 

Though i noticed a lot of "file changed on disk" popups. Is this maybe a regression from https://github.com/ipyflow/ipyflow/issues/145 ? Or maybe it is because i am using the new jupyerlab 4 collaborative functionality ? 

![disk_change_regression](https://github.com/ipyflow/ipyflow/assets/17649269/15646b65-93b3-49a1-9f95-48bed7cb4878)

I am using ipyflow==0.0.199 and the following jupyter versions:

Selected Jupyter core packages...
IPython          : 8.16.1
ipykernel        : 6.25.2
ipywidgets       : 8.1.2
jupyter_client   : 8.4.0
jupyter_core     : 5.4.0
jupyter_server   : 2.13.0
jupyterlab       : 4.1.5
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.11.2

**Comment by smacke** [comment]
Thanks for giving it a try, and very much appreciate the issue! Likely ipyflow's own autosave is probably breaking with the RTC -- I'll have to take a look and see if I can disable it when RTC is on.

**Comment by smacke** [comment]
Yep, this was indeed a regression. I've pushed a fix, you can pick it up by running `pip install --upgrade ipyflow`. Thanks again for giving it a try and for the helpful report!

**Comment by quantum-byte** [comment]
Wow that was fast! Thank you and you are welcome :smile
